.Dd September 6, 2025
.Dt DCHAT 8
.Os
.Sh NAME
.Nm dchatd
.Nd door-based chat daemon
.
.Sh DESCRIPTION
The
.Nm
daemon exchanges messages between 
.Xr dchat 1
clients. You can control it with
.Xr dchatadm 8 .
.Sh SEE ALSO
.Xr door_call 3C ,
.Xr door_create 3C ,
.Xr door_return 3C ,
.Xr door_ucred 3C ,
.Xr fattach 2 ,
.Xr fdetach 2
.Sh AUTHORS
.An "Robert D. French" Aq Mt robert@robertdfrench.me
